<a href="https://colab.research.google.com/github/KaranSharma0712/Learning-NLP/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
x=torch.rand(2,2)
print(x)
print(x.dtype)
print(x.size())

tensor([[0.9976, 0.7996],
        [0.5244, 0.6651]])
torch.float32
torch.Size([2, 2])


In [ ]:
x=torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
#tensor to numpy array
import numpy as np

In [ ]:
a=torch.ones(5)
print(a)
print(type(a))
b=a.numpy()
print(b)
print(type(b))
#but both will point to same memory location so changes in any of the one
#will reflect in the other

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
x=torch.rand(3,requires_grad=True)

In [ ]:
print(x)

tensor([0.6826, 0.4979, 0.8967], requires_grad=True)


In [ ]:
y=x+2
print(y)

tensor([2.6826, 2.4979, 2.8967], grad_fn=<AddBackward0>)


In [ ]:
z=y*y*2
z=z.mean()
print(z)

tensor(14.5511, grad_fn=<MeanBackward0>)


In [ ]:
#z is scalar here i.e only one value
z.backward()# since a is a single value here, therefore we do not need argument in backward function.
print(x.grad)
# it actually uses jacobian product to find gradient

tensor([7.1536, 6.6611, 7.7245])


In [ ]:
#if z is a vector
z=y*y*2
print(z)
v=torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([14.3926, 12.4790, 16.7816], grad_fn=<MulBackward0>)
tensor([ 8.2266, 16.6526,  7.7361])


In [ ]:
# 3 methods for stopping pytorch from creating gradient function and tracking the history in our computational graph
#x.require_grad_(False)
#x.detach()
#with torch.no_grad()

In [ ]:
weights = torch.ones(4,requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()#very imp step

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
