<a href="https://colab.research.google.com/github/KaranSharma0712/Learning-NLP/blob/main/pytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [ ]:
x=torch.rand(2,2)
print(x)
print(x.dtype)
print(x.size())

tensor([[0.9976, 0.7996],
        [0.5244, 0.6651]])
torch.float32
torch.Size([2, 2])


In [ ]:
x=torch.tensor([2.5,0.1])
print(x)

tensor([2.5000, 0.1000])


In [ ]:
#tensor to numpy array
import numpy as np

In [ ]:
a=torch.ones(5)
print(a)
print(type(a))
b=a.numpy()
print(b)
print(type(b))
#but both will point to same memory location so changes in any of the one
#will reflect in the other

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
x=torch.rand(3,requires_grad=True)

In [ ]:
print(x)

tensor([0.6826, 0.4979, 0.8967], requires_grad=True)


In [ ]:
y=x+2
print(y)

tensor([2.6826, 2.4979, 2.8967], grad_fn=<AddBackward0>)


In [ ]:
z=y*y*2
z=z.mean()
print(z)

tensor(14.5511, grad_fn=<MeanBackward0>)


In [ ]:
#z is scalar here i.e only one value
z.backward()# since a is a single value here, therefore we do not need argument in backward function.
print(x.grad)
# it actually uses jacobian product to find gradient

tensor([7.1536, 6.6611, 7.7245])


In [ ]:
#if z is a vector
z=y*y*2
print(z)
v=torch.tensor([0.1,1.0,0.001],dtype=torch.float32)
z.backward(v)
print(x.grad)

tensor([14.3926, 12.4790, 16.7816], grad_fn=<MulBackward0>)
tensor([ 8.2266, 16.6526,  7.7361])


In [ ]:
# 3 methods for stopping pytorch from creating gradient function and tracking the history in our computational graph
#x.require_grad_(False)
#x.detach()
#with torch.no_grad()

In [ ]:
weights = torch.ones(4,requires_grad=True)
for epoch in range(3):
  model_output = (weights*3).sum()
  model_output.backward()
  print(weights.grad)
  weights.grad.zero_()#very imp step

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


In [2]:
#Linear regression with pytorch
X=torch.tensor([1,2,3,4],dtype=torch.float32)
Y=torch.tensor([2,4,6,8],dtype=torch.float32)

In [3]:
w=torch.tensor(0.0,dtype=torch.float32,requires_grad=True)

In [4]:
def forward(x):
  return w*x

In [5]:
def loss(y,y_predicted):
  return((y_predicted-y)**2).mean()

In [6]:
print(f'Prediction before training : f(5) = {forward(5):.3f}')

Prediction before training : f(5) = 0.000


In [26]:
learning_rate=0.01
n_iter=100

In [27]:
for epoch in range(n_iter):
  y_pred=forward(X)
  l=loss(Y,y_pred)
  l.backward()
  with torch.no_grad():
    w-=learning_rate*w.grad
  w.grad.zero_()
  if epoch %5 ==0:
    print(f'epoch {epoch+1}:w = {w:.3f},loss={l:.8f}')
print(f'Prediction after training : f(5) = {forward(5):.3f}')

epoch 1:w = 2.000,loss=0.00000000
epoch 6:w = 2.000,loss=0.00000000
epoch 11:w = 2.000,loss=0.00000000
epoch 16:w = 2.000,loss=0.00000000
epoch 21:w = 2.000,loss=0.00000000
epoch 26:w = 2.000,loss=0.00000000
epoch 31:w = 2.000,loss=0.00000000
epoch 36:w = 2.000,loss=0.00000000
epoch 41:w = 2.000,loss=0.00000000
epoch 46:w = 2.000,loss=0.00000000
epoch 51:w = 2.000,loss=0.00000000
epoch 56:w = 2.000,loss=0.00000000
epoch 61:w = 2.000,loss=0.00000000
epoch 66:w = 2.000,loss=0.00000000
epoch 71:w = 2.000,loss=0.00000000
epoch 76:w = 2.000,loss=0.00000000
epoch 81:w = 2.000,loss=0.00000000
epoch 86:w = 2.000,loss=0.00000000
epoch 91:w = 2.000,loss=0.00000000
epoch 96:w = 2.000,loss=0.00000000
Prediction after training : f(5) = 10.000


In [28]:
import torch.nn as nn

In [37]:
X=torch.tensor([1,2,3,4],dtype=torch.float32)
Y=torch.tensor([2,4,6,8],dtype=torch.float32)

4 1


In [38]:
def forward(x):
  return w*x

In [ ]:
print(f'Prediction before training : f(5) = {forward(5):.3f}')

In [31]:
loss = nn.MSELoss()

In [35]:
optimizer = torch.optim.SGD([w],lr=learning_rate)#Stochastic Gradient Descent

In [36]:
learning_rate=0.01
n_iter=20
for epoch in range(n_iter):
  y_pred=forward(X)
  l=loss(Y,y_pred)
  l.backward()
  optimizer.step()
  optimizer.zero_grad()
if epoch %2 ==0:
    print(f'epoch {epoch+1}:w = {w:.3f},loss={l:.8f}')
print(f'Prediction after training : f(5) = {forward(5):.3f}')

Prediction after training : f(5) = 10.000


In [ ]:
X=torch.tensor([[1],[2],[3],[4]],dtype=torch.float32)
Y=torch.tensor([[2],[4],[6],[8]],dtype=torch.float32)

n_samples,n_features=X.shape
print(n_samples,n_features)

In [2]:
import torch
import torchvision
from torch.utils.data import Dataset
import numpy as np


class WineDataset(Dataset):

    def __init__(self, transform=None):
        xy = np.loadtxt('/content/wine.csv', delimiter=',', dtype=np.float32, skiprows=1)
        self.n_samples = xy.shape[0]

        # note that we do not convert to tensor here
        self.x_data = xy[:, 1:]
        self.y_data = xy[:, [0]]

        self.transform = transform

    def __getitem__(self, index):
        sample = self.x_data[index], self.y_data[index]

        if self.transform:
            sample = self.transform(sample)

        return sample

    def __len__(self):
        return self.n_samples

# Custom Transforms
# implement __call__(self, sample)
class ToTensor:
    # Convert ndarrays to Tensors
    def __call__(self, sample):
        inputs, targets = sample
        return torch.from_numpy(inputs), torch.from_numpy(targets)

class MulTransform:
    # multiply inputs with a given factor
    def __init__(self, factor):
        self.factor = factor

    def __call__(self, sample):
        inputs, targets = sample
        inputs *= self.factor
        return inputs, targets

print('Without Transform')
dataset = WineDataset()
first_data = dataset[0]
features, labels = first_data
print(type(features), type(labels))
print(features, labels)

print('\nWith Tensor Transform')
dataset = WineDataset(transform=ToTensor())
first_data = dataset[0]
features, labels = first_data
print(type(features), type(labels))
print(features, labels)

print('\nWith Tensor and Multiplication Transform')
composed = torchvision.transforms.Compose([ToTensor(), MulTransform(4)])
dataset = WineDataset(transform=composed)
first_data = dataset[0]
features, labels = first_data
print(type(features), type(labels))
print(features, labels)

Without Transform
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
 2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03] [1.]

With Tensor Transform
<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])

With Tensor and Multiplication Transform
<class 'torch.Tensor'> <class 'torch.Tensor'>
tensor([5.6920e+01, 6.8400e+00, 9.7200e+00, 6.2400e+01, 5.0800e+02, 1.1200e+01,
        1.2240e+01, 1.1200e+00, 9.1600e+00, 2.2560e+01, 4.1600e+00, 1.5680e+01,
        4.2600e+03]) tensor([1.])
